---
title: "Fancy Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)

data("rest_inspec")

rest_inspec <-
  rest_inspec %>% 
  filter(boro == "MANHATTAN" & score %in% 0:100)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Score Distribution based on Cuision Type

```{r}
rest_inspec %>% 
  group_by(cuisine_description) %>% 
  mutate(text_label = str_c("Restaurant: ",dba,
                            "\nScore: ",score)) %>%
  mutate(cuisine_description = 
           case_when(cuisine_description == 
                       "Latin (Cuban, Dominican, Puerto Rican, South & Central American)" ~"Latin", 
                     cuisine_description == "Bottled beverages, including water, sodas, juices, etc." ~ "Bottled beverages",T ~ cuisine_description)) %>% 
  plot_ly(x = ~cuisine_description,y = ~ score,
          text = ~ text_label,color = ~ cuisine_description,
          type = "box",alpha = 0.5) %>% 
  layout(xaxis = list(tickangle = -45,tickfont = list(size = 7)),
         legend = list(font = list(size = 7)))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Number of Restaurants under each Grade

```{r}
rest_inspec %>% 
  drop_na(grade) %>% 
  group_by(grade)%>% 
  count(grade) %>%
  plot_ly(x = ~grade,y = ~ n,type = "bar")
```

### Average Score for Different zipcode

```{r}
rest_inspec %>% mutate(zipcode = as.factor(zipcode)) %>% 
  group_by(zipcode) %>% 
  summarize(avg_score = mean(score)) %>% 
  plot_ly(x = ~zipcode,y = ~ avg_score,
         type = "scatter",mode = "line")
```

